### ISSUE TITLE
Is the example supposed to be run from IEX?

### ISSUE THREAD

**Issue by grant-zukowski-xumo** [kim-company/membrane_hls_plugin#11]
Hi,

I'm new to membrane, but I have many cases where I need to ingest HLS as a source.  I'm trying to get your example to run, but when I paste the module into IEx I get:

```
error: Membrane.RTMP.Source.__struct__/1 is undefined, cannot expand struct Membrane.RTMP.Source. Make sure the struct name is correct. If the struct name exists and is correct but it still cannot be found, you likely have cyclic module usage in your code
└─ iex:18: Pipeline.handle_init/2
```

**Comment by philipgiuliani** [comment]
I guess you were talking about this example https://github.com/kim-company/membrane_hls_plugin/commit/1252a3a00c506e7165c5624e469a8167c00389e9#diff-05f8e2705e28496ad6fec538a76a2875b823a92113c97baa539665cac0fa0ef9L25 which is actually RTMP to HLS. We will clarify that and describe that example a little bit better.

For ingesting HLS you need to look at the `HLS.Source`: https://github.com/kim-company/membrane_hls_plugin/blob/main/lib/membrane/hls/source.ex The HLS source will notify you about the master playlist, and then you can proceed to add a specific demuxer or decoder.

Note that this plugin only works for HLS playlists with AAC or TS segments and not for M4S segments yet.

**Comment by grant-zukowski-xumo** [comment]
Hi, and thank you for getting back to me so quickly.  I'm hoping to get a prototype of this working, most of our use case is ingesting HLS then outputting various other formats, usually HLS again.  

Anyway, I got your example to run: I was using `iex -S mix` instead of just `iex`.

I'm now trying to make a sample that I can run.  I can close this issue and open a new one, or I can ask here:

```
    spec =
      child(:source, %Membrane.HLS.Source{
        # reader: %Membrane.HLS.Reader{},
        master_playlist_uri: "https://dangertv-us.xumo.wurl.tv/playlist.m3u8"
      })
```
** (ArgumentError) the following keys must also be given when building struct Membrane.HLS.Source: [:reader]
    (membrane_hls_plugin 0.1.0) expanding struct: Membrane.HLS.Source.__struct__/1
    iex:3: (file)
    
    Says I need a reader.  I've been looking at the tests and through the code, but I can't find an example of a reader yet.

**Comment by grant-zukowski-xumo** [comment]
I was able to start making an example.  I can see you have a test that does a source has hls.  Even using that example, I keep getting stuck on the protocol part of the reader.  Can you please post me a simple example of a module reading with HLS?  

```
Mix.install([
  :membrane_core,
  # :membrane_rtmp_plugin,
  # :membrane_aac_plugin,
  # :membrane_h26x_plugin,
  # :membrane_tee_plugin,
  # {:membrane_ffmpeg_transcoder_plugin, "~> 1.1"},
  {:membrane_hls_plugin, github: "kim-company/membrane_hls_plugin"}
])


defmodule My.Reader do
  defstruct []
end

defimpl Membrane.HLS.Reader, for: My.Reader do
  @impl true
  def read(_, %URI{path: path}, _), do: File.read(path)

  @impl true
  def exists?(_, %URI{path: path}) do
    case File.stat(path) do
      {:ok, _} -> true
      {:error, _} -> false
    end
  end
end

defmodule Membrane.Demo.HLSIn do
  @moduledoc """
  Pipeline that contains HLS input element.
  """

  use Membrane.Pipeline

  @impl true
  def handle_init(_ctx, _opts) do
    spec =
      child(:source, %Membrane.HLS.Source{
        reader: %My.Reader{},
        master_playlist_uri: "<real hls stream on the internet>"
      })

    {[spec: spec], %{}}
  end
end

{:ok, _supervisor, _pipeline} = Membrane.Pipeline.start_link(Membrane.Demo.HLSIn, [])
```

Here is what I have so far, no matter how I try to define the protocol, I get this error.  I can see your example of support reader, and even if I copy an use that exactly, I keep getting this error.

```

23:32:04.549 [error] <0.240.0>/:source Error occured in Membrane Element:
** (Protocol.UndefinedError) protocol Membrane.HLS.Reader not implemented for %My.Reader{} of type My.Reader (a struct). There are no implementations for this protocol.
    (membrane_hls_plugin 0.1.0) lib/membrane/hls/reader.ex:1: Membrane.HLS.Reader.impl_for!/1
    (membrane_hls_plugin 0.1.0) lib/membrane/hls/source.ex:106: Membrane.HLS.Source.handle_info/3
    (membrane_core 1.1.2) lib/membrane/core/callback_handler.ex:139: Membrane.Core.CallbackHandler.exec_callback/4
    (membrane_core 1.1.2) lib/membrane/core/callback_handler.ex:69: Membrane.Core.CallbackHandler.exec_and_handle_callback/5
    (membrane_core 1.1.2) lib/membrane/core/element.ex:299: Membrane.Core.Element.handle_info/2
    (stdlib 5.2.3) gen_server.erl:1095: :gen_server.try_handle_info/3
    (stdlib 5.2.3) gen_server.erl:1183: :gen_server.handle_msg/6
    (stdlib 5.2.3) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
```

**Comment by grant-zukowski-xumo** [comment]
@philipgiuliani Just pinging you to make sure you saw my response.

**Comment by dmorn** [comment]
Hey @grant-zukowski-xumo. In elixir scripts you should use the [consolidate_protocols: false] option of Mix.install, that's the error you're experiencing.

**Comment by grant-zukowski-xumo** [comment]
Hi @dmorn thank you for that info.  Can you help me get unstuck.  I can't figure out how to get a simple HLS source running.
